### ISSUE TITLE
Failed Startup after coming back to this app

### ISSUE THREAD

**Issue by Iceman248** [exadel-inc/CompreFace#1001]
**Describe the bug**
I used to use once single container version was available for unRAID. I was on 0.6.1. I couldn't login anymore, decided to wipe and start fresh since I didn't do much with it initially, but now I have a new doorbell camera that I can use with it, so I'm back, but even after a clean reinstall, I cannot create an account, getting same error when trying to login on previous install. Same thing with both 0.6.1, and latest 1.1.0 version. I looked at log and it seems to fail at compreface-admin over and over.

**To Reproduce**
Leave default 4 options that seem to use internal database from unRAID template, also clear them all which I think does same thing anyways. Either way is a problem.

**Expected behavior**
It it load up successfully so I can create and account and login.

**Desktop (please complete the following information):**
 - OS: unRAID
 - Browser: Chrome
 - Version 108.0.5359.125

**Additional context**
Log attached next post.

**Comment by Iceman248** [comment]
[101371cb6ca6406a23c481e25d4efd8b834df276c077e06cd775e6c305834c43-json.log](https://github.com/exadel-inc/CompreFace/files/10260559/101371cb6ca6406a23c481e25d4efd8b834df276c077e06cd775e6c305834c43-json.log)

**Comment by pospielov** [comment]
```{"log":"2022-12-19 15:23:44.181 UTC [31] LOG:  could not bind IPv6 address \"::1\": Cannot assign requested address\n","stream":"stdout","time":"2022-12-19T15:23:44.181715269Z"}```
```{"log":"2022-12-19 15:23:44.181 UTC [31] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.\n","stream":"stdout","time":"2022-12-19T15:23:44.181725593Z"}```

This is from your logs. It looks like it can't start the database. It says that the port is taken by some other application. 
That is strange, as I don't see how postgres can be run twice inside a container
Is it possible you expose the 5432 outside and some other application took it?

I would also recommend deleting the db volume as well:
```docker volume rm compreface-db```

**Comment by Iceman248** [comment]
Now that you mention that, one thing I did in between using this was actually install postgres for something else that does use my server's 5432 port. Would that be conflicting then? If so, since I have postgres now anyways, should I just be using it via the external database option?

**Comment by Iceman248** [comment]
Although I shutdown the other postgres and it still doesn't work, still getting error not expected about compreface-admin.

**Comment by pospielov** [comment]
Sorry for a long response
It can't use this PostgresSQL as an external option because to use it as an external option, the database should be set up for this (user and database should be created, only then it will be initialized by CompreFace)
Is the error the same after you shut down other Postgres?
Can you connect to the container and find out what process takes 5432 port?

**Comment by Iceman248** [comment]
No problem, thanks. Sorry I didn't update this. I set up a new database within my postgres container for CompreFace and then configured CompreFace to use it and it now works.

**Comment by jonahgcarpenter** [comment]
im getting this same issue on a fresh install of unraid, but an older server is working perfectly fine. I also know for a fact im not running another server on the same port
