### ISSUE TITLE
Compreface-core fails on authorization failed

### ISSUE THREAD

**Issue by Elytum** [exadel-inc/CompreFace#1005]
Hi, for some reason when trying to run with GPU I get the following error:

ERROR [internal] load metadata for docker.io/library/compreface-core-ba  0.6s
[internal] load metadata for docker.io/library/compreface-core-base:base-cuda100-py37:
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
ERROR: Service 'compreface-core' failed to build : Build failed

Here's how to reproduce:
Clone the repository
Go to dev
Run "docker-compose -f docker-compose-gpu.yml up -d"

Am I doing anything wrong ? Thanks a lot anyway, CPU only is awesome (aside from the speed)

**Comment by pospielov** [comment]
The easiest way to use GPU version is to run it from the release:
https://github.com/exadel-inc/CompreFace/releases/download/v1.1.0/CompreFace_1.1.0.zip
all you need is to download the archive, open the custom-builds folder, and choose the custom build with the GPU prefix

**Comment by Elytum** [comment]
Works perfectly, thanks a lot !
