### ISSUE TITLE
compreface-core start failed

### ISSUE THREAD

**Issue by guossf** [exadel-inc/CompreFace#1008]
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19 (64bit) on [Thu Jan  5 03:41:08 2023] ***
compiled with version: 10.2.1 20210110 on 10 April 2022 08:56:46
os: Linux-5.18.15-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 28 09:26:15 EDT 2022
nodename: 6f570f371950
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /app/ml
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33

**Comment by guossf** [comment]
kernel: traps: uwsgi[393965] trap invalid opcode ip:7f6ee2720980 sp:7fff423216a8 error:0 in _pywrap_tensorflow_internal.so[7f6ed7668000+4154a000]

**Comment by pospielov** [comment]
Could you share more information? 
What CompreFace build are you running?
Does `compreface-core` container fail?
Could you send the full `compreface-core` container log?

**Comment by guossf** [comment]
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19 (64bit) on [Fri Jan  6 02:04:11 2023] ***
compiled with version: 10.2.1 20210110 on 10 April 2022 08:56:46
os: Linux-5.18.15-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 28 09:26:15 EDT 2022
nodename: 8c3657f1b9cd
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /app/ml
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:3000 fd 3
Python version: 3.7.13 (default, Apr  7 2022, 05:38:27)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x558fe6906390
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218712 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19 (64bit) on [Fri Jan  6 02:05:12 2023] ***
compiled with version: 10.2.1 20210110 on 10 April 2022 08:56:46
os: Linux-5.18.15-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 28 09:26:15 EDT 2022
nodename: 8c3657f1b9cd
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /app/ml
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:3000 fd 3
Python version: 3.7.13 (default, Apr  7 2022, 05:38:27)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x5593070e8390
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218712 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19 (64bit) on [Fri Jan  6 02:06:13 2023] ***
compiled with version: 10.2.1 20210110 on 10 April 2022 08:56:46
os: Linux-5.18.15-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 28 09:26:15 EDT 2022
nodename: 8c3657f1b9cd
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /app/ml
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:3000 fd 3
Python version: 3.7.13 (default, Apr  7 2022, 05:38:27)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55bab13ce390
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218712 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19 (64bit) on [Fri Jan  6 02:07:14 2023] ***
compiled with version: 10.2.1 20210110 on 10 April 2022 08:56:46
os: Linux-5.18.15-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 28 09:26:15 EDT 2022
nodename: 8c3657f1b9cd
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /app/ml
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:3000 fd 3
Python version: 3.7.13 (default, Apr  7 2022, 05:38:27)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x5632a22db390
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218712 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***

**Comment by guossf** [comment]
version  is v1.0.0 ,only compreface-core container fail

**Comment by guossf** [comment]
Docker logs 
Jan  6 10:05:12 localhost kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth71999bc: link becomes ready
Jan  6 10:05:12 localhost kernel: br-18b49d7c9da4: port 2(veth71999bc) entered blocking state
Jan  6 10:05:12 localhost kernel: br-18b49d7c9da4: port 2(veth71999bc) entered forwarding state
Jan  6 10:05:13 localhost kernel: traps: uwsgi[3613310] trap invalid opcode ip:7f53a7806980 sp:7fffdf61c5b8 error:0 in _pywrap_tensorflow_internal.so[7f539c74e000+4154a000]
Jan  6 10:05:13 localhost dockerd: time="2023-01-06T10:05:13.286908241+08:00" level=info msg="ignoring event" container=8c3657f1b9cd45c52347541634cabb52372fdbbca303ba13f4604e55e8663bbc module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jan  6 10:05:13 localhost containerd: time="2023-01-06T10:05:13.286793077+08:00" level=info msg="shim disconnected" id=8c3657f1b9cd45c52347541634cabb52372fdbbca303ba13f4604e55e8663bbc
Jan  6 10:05:13 localhost containerd: time="2023-01-06T10:05:13.288398195+08:00" level=warning msg="cleaning up after shim disconnected" id=8c3657f1b9cd45c52347541634cabb52372fdbbca303ba13f4604e55e8663bbc namespace=moby
Jan  6 10:05:13 localhost containerd: time="2023-01-06T10:05:13.288430498+08:00" level=info msg="cleaning up dead shim"
Jan  6 10:05:13 localhost containerd: time="2023-01-06T10:05:13.302584312+08:00" level=warning msg="cleanup warnings time=\"2023-01-06T10:05:13+08:00\" level=info msg=\"starting signal loop\" namespace=moby pid=3613396 runtime=io.containerd.runc.v2\n"
Jan  6 10:05:13 localhost kernel: br-18b49d7c9da4: port 2(veth71999bc) entered disabled state
Jan  6 10:05:13 localhost kernel: veth08ed74a: renamed from eth0
Jan  6 10:05:13 localhost kernel: br-18b49d7c9da4: port 2(veth71999bc) entered disabled state
Jan  6 10:05:13 localhost kernel: device veth71999bc left promiscuous mode
Jan  6 10:05:13 localhost kernel: br-18b49d7c9da4: port 2(veth71999bc) entered disabled state
Jan  6 10:06:13 localhost kernel: br-18b49d7c9da4: port 2(veth04ffb0f) entered blocking state
Jan  6 10:06:13 localhost kernel: br-18b49d7c9da4: port 2(veth04ffb0f) entered disabled state
Jan  6 10:06:13 localhost kernel: device veth04ffb0f entered promiscuous mode
Jan  6 10:06:13 localhost containerd: time="2023-01-06T10:06:13.355834562+08:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Jan  6 10:06:13 localhost containerd: time="2023-01-06T10:06:13.355994806+08:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Jan  6 10:06:13 localhost containerd: time="2023-01-06T10:06:13.356068895+08:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Jan  6 10:06:13 localhost containerd: time="2023-01-06T10:06:13.356361540+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/8c3657f1b9cd45c52347541634cabb52372fdbbca303ba13f4604e55e8663bbc pid=3620540 runtime=io.containerd.runc.v2
Jan  6 10:06:13 localhost kernel: eth0: renamed from veth2eab99c
Jan  6 10:06:13 localhost kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth04ffb0f: link becomes ready
Jan  6 10:06:13 localhost kernel: br-18b49d7c9da4: port 2(veth04ffb0f) entered blocking state
Jan  6 10:06:13 localhost kernel: br-18b49d7c9da4: port 2(veth04ffb0f) entered forwarding state
Jan  6 10:06:14 localhost kernel: traps: uwsgi[3620560] trap invalid opcode ip:7f29c709c980 sp:7fff6d008868 error:0 in _pywrap_tensorflow_internal.so[7f29bbfe4000+4154a000]

**Comment by guossf** [comment]
I need help ,i repeated this question again ！！！ 
System information:
Os: CentOS Linux release 7.9.2009 (Core)
Kernel version: Linux localhost.localdomain 6.1.3-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jan  3 09:54:50 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
Docker version:    20.10.22
Comperface : 1.0.0

**Comment by pospielov** [comment]
Does your CPU support AVX?
You can run the command `lscpu | grep avx` to understand.

**Comment by guossf** [comment]
运行失败的主机上CPU不支持AVX，有一台主机CPU不支持AVX，但是也可以正常运行Comperface-core.

**Comment by guossf** [comment]
The CPU on the failed host does not support AVX. One host CPU does not support AVX, but it can run Comperface core normally。

**Comment by guossf** [comment]
The CPU on the failed host does not support AVX. One host CPU does not support AVX, but it can run Comperface core normally.

**Comment by guossf** [comment]
Thank you. The problem has been solved. The virtual machine does not support AVX. After adjusting the CPU mode of the virtual machine, it runs normally.
