### ISSUE TITLE
Error while running the application on windows after install

### ISSUE THREAD

**Issue by ersaurabh101** [exadel-inc/CompreFace#1022]
**Describe the bug**
I have successfully installed it on docker as guided

**To Reproduce**
After installation i have created a user, and when i am trying to add a service, it is giving me this error -

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/50316624/216006821-169d704b-dfe0-4fcb-91eb-f48b2896b17d.png">

**Desktop (please complete the following information):**
I am on windows 11

**Comment by pospielov** [comment]
Could you run `docker-compose logs` and upload the file here?

**Comment by ersaurabh101** [comment]
I downloaded another zip and things worked. Now i have successfully logged in. I want to ask couple of questions regarding best practices, do i open another tread for that ?

**Comment by pospielov** [comment]
It's better to create a discussion for this:
https://github.com/exadel-inc/CompreFace/discussions
