### ISSUE TITLE
mobilenetv2_1_0 symbols

### ISSUE THREAD

**Issue by Viper-Bit** [exadel-inc/CompreFace#1025]
how can i download mobilenetv2_1_0.json for mask detection ?
i want to convert it to onnx and its not provided in [mobilenetv2_1_0.zip](https://drive.google.com/file/d/1DYUIroNXkuYKQypYtCxQvAItLnrTTt5E)

thx

**Comment by SaeedAryanmehrIsf** [comment]
This is my request too 
TanQ

**Comment by IvanKurnosov** [comment]
We have no json file for this architecture, but you can produce it by yourself as described here: https://mxnet.apache.org/versions/1.7/api/python/docs/tutorials/packages/gluon/blocks/save_load_params.html

Firstly, you need to load pretrained model the same way we do it in embedding-calculator/src/services/facescan/plugins/insightface/facemask/facemask.py in 64-66 lines.

Then, you need to call model.export() and it will produce two files .params and .json.

**Comment by Viper-Bit** [comment]
@IvanKurnosov  thx for hint, for others that want to do to that i used bellow code:

```python
import mxnet as mx
import numpy as np
from mxnet.gluon.model_zoo import vision

ctx = mx.cpu()

model = vision.mobilenet_v2_1_0(classes=3, ctx=ctx)

model_path = './mobilenetv2_1_0.params'
model.load_parameters(str(model_path), ctx=ctx)
model.hybridize(static_alloc=True, static_shape=True)
model(mx.random.uniform(shape=(1, 3, 224, 224)))
model.export('model')

sym = './model-symbol.json'
params = './model-0000.params'

in_shapes = [(1, 3, 224, 224)]
dynamic_input_shapes = [(None, 3, 224, 224)]
in_types = [np.float32]

onnx_file = './model.onnx'

converted_model_path = mx.onnx.export_model(sym, params, in_shapes, in_types, onnx_file,
                                            dynamic=True, dynamic_input_shapes=dynamic_input_shapes)
```

**Comment by sivi-shahab** [comment]
can i get this file [mobilenetv2_1_0.zip](https://drive.google.com/file/d/1DYUIroNXkuYKQypYtCxQvAItLnrTTt5E)
