### ISSUE TITLE
Out of memory error on SubCenter-ArcFace-r100-gpu

### ISSUE THREAD

**Issue by sjkjs** [exadel-inc/CompreFace#1061]
When running on an 8GB NVidia Tesla P4, I get an out of memory error starting the SubCenter-ArcFace-r100-gpu build:

`PluginError: insightface.Calculator@arcface-r100-msfdrop75 error - simple_bind error. Arguments:\\ndata: (1, 3, 112, 112)\\nTraceback (most recent call last):\\n  File \\\"../src/storage/./pooled_storage_manager.h\\\", line 160\\nMXNetError: cudaMalloc retry failed: out of memory`

nvidia-smi shows two uwsgi processes using around 6GB memory:

```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3240	 C   uwsgi                            3233MiB |
|    0   N/A  N/A      3241	 C   uwsgi                            2727MiB |
+-----------------------------------------------------------------------------+
```

Interestingly the GPU still has over 1.5GB RAM free which is not being used.

Is it correct that it's using this much memory, and if so what is the minimum requirement to use it?

**Comment by pospielov** [comment]
https://github.com/exadel-inc/CompreFace/issues/1034#issuecomment-1481932849
I gave a detailed answer here.
In short - you can run it on one process or use an older version.

**Comment by sjkjs** [comment]
Thank you. I will close this issue since there's already one open.
