### ISSUE TITLE
Cannot start the container due to python library

### ISSUE THREAD

**Issue by lordratner** [exadel-inc/CompreFace#1064]
**Describe the bug**

When running `docker compose up -d` it fails with this error:

`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/local/lib/python3.7/site-packages/numpy-1.19.5.dist-info: invalid argument`

It fails during the extraction of this image: f7b64384d90e

I'm running it in a Proxmox LXC. The LXC has python 3.9, not 3.7, but I didn't see that anywhere in the instructions as an issue, and I was under the impression it didn't matter for Docker. 

**To Reproduce**

1. Follow installation instructions. 

**Desktop (please complete the following information):**

 - OS: Debian

**Logs**

Run those commands and attach result to the ticket:

Doesn't start, so no logs

**Additional context**

This started after updating Proxmox, which I assume updated something (python?) in the LXC containers. But I still don't see where in the instructions I need python 3.7 to install in Docker, and I'm not experienced enough to know the difference here.

Thanks!

**Comment by lordratner** [comment]
For clarity, this was working before the Proxmox Update. When the server restarted the container started too, but docker compose did not automatically start the containers. Calling `docker compose up -d` started a pull, where this problem occurred.

**Comment by pospielov** [comment]
I googled it, and it looks like this is a docker problem.
Just a couple of links with discussion, I hope they will help:
https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/
https://github.com/moby/moby/issues/43576
https://forum.proxmox.com/threads/proxmox-lxc-docker-pull-issues.29781/
