### ISSUE TITLE
how help optimizing model parameters

### ISSUE THREAD

**Issue by neozhu** [exadel-inc/CompreFace#1069]
I am currently testing a model and have noticed a significant difference between two photos when compared. However, the similarity score between the two photos is still around 98%. I am using the latest version of docker-compose to deploy the testing environment. Can someone please advise me on how to adjust the model parameters to optimize its performance?
Thank you in advance for your help!
<img width="1257" alt="image" src="https://github.com/exadel-inc/CompreFace/assets/1549611/f2f87afa-8265-4ddd-94a0-b14dd053f36e">

**Comment by pospielov** [comment]
https://github.com/exadel-inc/CompreFace/blob/master/docs/Custom-builds.md#how-to-run-custom-builds
I can recommend you run `Mobilenet` or `SubCenter-ArcFace-r100` custom builds. They show better performance on Asians.

**Comment by neozhu** [comment]
Thank you very much for your assistance. Yes, switching to SubCenter-ArcFace-r100 has yielded excellent results.
