### ISSUE TITLE
 Inquiry Regarding max_detect_size=640 for Improved Detection Accuracy

### ISSUE THREAD

**Issue by neozhu** [exadel-inc/CompreFace#1072]
Hi there,

I have a question regarding the "max_detect_size" parameter in your docker-compose file. Specifically, I would like to inquire about the image size it refers to for accurate object detection. Does it pertain to the input image size, which is set as 640x640, or does it specifically relate to the size of the face in the image?

My intention is to determine the optimal image size for achieving more precise detection results. Could you kindly advise on the recommended best size for this parameter? Any insights or guidance you can provide would be greatly appreciated.

Thank you very much for your attention and assistance. I look forward to your prompt response.

**Comment by pospielov** [comment]
Thanks for the question. We forgot to add it to our documentation. 
`max_detect_size` determines the max input size before face detection. 
So if this equals 640, but you send an image with a resolution 1024*768, then CompreFace will resize the image to 640*480.
If the original image is 320*240, it won't be resized.
This is done to speedup the face detection process.
Also, if you have an image with big resolution, CompreFace will reduce it for face detection. Then, for face recognition, it will crop the faces from the original image, and resize them to the appropriate size for face recognition. 
All in all, depending on the build, the neural network requires different input image with face, but it's not big about 200*200 pixels. 
This is why to get the best face recognition performance, you need need to get a face around 200*200 size. Increasing resolution more than this, won't increase the accuracy a lot.

**Comment by pospielov** [comment]
Thanks for the question, we forgot to add it to our documentation 
max_detect_size determines max size of the image to send to face detection service.
Here is the face recognition flow:
1. Resize the input image for face detection. Here, if the input width or height is higher than max_detect_size, CompreFace will resize the input image. E.g. if max_detect_size=640, and input image is 1024*768, it will be resized to 640*480. Face detector is quite sensitive and doesn't require big images, it can find faces of about 20*20 pixels. This is why there is no sense in sending there big picture, especially if we expect faces to be quite big. 
2. Crop faces from the input image. It means that we crop the faces not from the resized image, but from the original image, so we will preserve the input image quality. It doesn't depend anyhow on max_detect_size param 
3. Resize faces to the standard size. This size depends on face recognition model, and it's about 200*200 pixels. So sending faces bigger than that won't increase the accuracy a lot. This doesn't depend anyhow on max_detect_size param 

So, it makes sense to change this param only if you have problems with face detection, not face recognition. E.g. you are trying to recognize faces in the class, you have 4k photo, but the faces are relatively small, so they won't be detected if we rescale the image to 640*480

**Comment by neozhu** [comment]
Thank you for providing such detailed information. I appreciate it
