### ISSUE TITLE
Lost password...

### ISSUE THREAD

**Issue by lee-costa** [exadel-inc/CompreFace#1083]
For some strange reason, I can no longer login even though I am sure of the password. I created another account and can see the other user but can't add the owner role to the new one (I understand that it's by design). 

Any way to recover without reinstalling?

**Comment by pospielov** [comment]
We have "forgot password" functionality, but it works only if you enable integration with the email server (we do not provide our email server).
To enable integration with the email server, you have to set five parameters in the .env file:
email_host=
email_username=
email_from=
email_password=
enable_email_server=
After you restart CompreFace, there will be "Forgot Password?" link on Login page, so you can use it to send the restoration password link.

There is another, more complex way to reset a password directly in database, but I hope this way will work

**Comment by lee-costa** [comment]
@pospielov I enabled the parameters in the .env file but I don't see a link anywhere. 

    email_host=smtp.gmail.com
    email_username=user@gmail.com
    email_from=user@gmail.com
    email_password=redacted
    enable_email_server=true

**Comment by lee-costa** [comment]
> Did you restart CompreFace?
> docker-compose down
> docker-compose up -d

Absolutely did.

**Comment by pospielov** [comment]
I just checked the flow, and it works:

![image](https://github.com/exadel-inc/CompreFace/assets/3736126/182b54b5-475e-41a7-95dc-cedfb8aabf5f)

It's the 1.2 unreleased version, but we didn't change it since 1.0, so it should be the same on 1.1.

Just one idea that came to my mind - did you use your real password or app password?
If you have enabled 2-step verification, you need an app password, your usual password won't work. 
Here is an instruction on how to get the app password:
https://support.google.com/mail/answer/185833

**Comment by lee-costa** [comment]
I was using the app password and still nothing. Disabled ad blocker, cleared cache etc. Is there a chance my Gmail server setting is missing something? I have configured as displayed above.

**Comment by pospielov** [comment]
Send me your .env file and docker-compose files:
compreface.support@exadel.com 
You can delete the app password

**Comment by pospielov** [comment]
BTW, how difficult is it for you to load all images from scratch? 
If it's not a big problem, you can just clear the database:
1. Stop CompreFace
docker-compose down
2. Run the command to see the list of volumes:
docker volume ls
3. Find volume with name <folder_with_compreface_name>_postgres-data
Probably it will be compreface_110_postgres-data
4. run: 
docker volume rm compreface_110_postgres-data
5. Start CompreFace again:
docker-compose up -d

**Comment by lee-costa** [comment]
I sent you the files as requested but also ended up following your instructions and dropping the database.

Thanks for your help!

**Comment by pospielov** [comment]
Just in case somebody comes across this thread:
I made a mistake here, the "reset password" functionality will be added only in CompreFace 1.2.
