### ISSUE TITLE
How do you find similarity percentage from euclidean distance of the embeddings

### ISSUE THREAD

**Issue by Code-beep12** [exadel-inc/CompreFace#1091]
Two images which showed a 98.838% similarity has a euclidean distance of 0.7619. How would i go about finding the similarity percentage. My aim is to store embeddings and later find the similarity of faces rather than calling the verify api of compreface repeatedly

**Comment by pospielov** [comment]
You can find the formula that we use to calculate the similarity from Euclidean distance here:
https://github.com/exadel-inc/CompreFace/blob/d10cf2f1d8d6f4a55ba918f391509a402e5b59eb/java/api/src/main/java/com/exadel/frs/core/trainservice/component/classifiers/EuclideanDistanceClassifier.java#L142
And coefficients here:
https://github.com/exadel-inc/CompreFace/blob/d10cf2f1d8d6f4a55ba918f391509a402e5b59eb/embedding-calculator/src/services/facescan/plugins/facenet/facenet.py#L141
https://github.com/exadel-inc/CompreFace/blob/d10cf2f1d8d6f4a55ba918f391509a402e5b59eb/embedding-calculator/src/services/facescan/plugins/insightface/insightface.py#L136C1-L136C19
However, if you don't need to compare similarities with CompreFace, you can just use distance and choose the threshold based on it.
We created similarity just to simplify understanding of choosing threshold.

**Comment by Code-beep12** [comment]
Thank you so much
