### ISSUE TITLE
Password - CompreFace in Docker Container for Windows

### ISSUE THREAD

**Issue by renaatdb** [exadel-inc/CompreFace#1190]
I installed Compreface in Docker Container for windows.
I lost Exadel Compreface password 
Where I can find the Password? In Docker?
Creating a new account is not possible (My mailadres already in use)
![comp](https://github.com/exadel-inc/CompreFace/assets/5012211/a2dc3cbf-9a92-41cf-b82b-7e081abc0fb5)

**Comment by TheMrRight** [comment]
I have the same issue. How did you fix it?

I was just testing it, and the I can't remember the password...

I tried deleting and making a new container.

But that email is still in use somehow? I just did a whole reinstall, I don't understand how that email can be still in use tho.

Can I not use that email address anymore, is it lost to the Ether?

**Comment by renaatdb** [comment]
Reinstalled Compreface (Container ) did the job. With the same pasword.
