### ISSUE TITLE
Unable to get running

### ISSUE THREAD

**Issue by MOpenlander** [exadel-inc/CompreFace#1241]
**Describe the bug**

Doing a clean install. Followed the getting started guide. The login UI gets stuck on Admin node loading... API and Core node have a checkmark. Eventually it times out and takes me to the login page. I create a user but it throws an "invalid credentials" error. I create another user and that one works.

**To Reproduce**

1. Download release zip
2. Unzip
3. Run docker compose up -d

**Expected behavior**

Expect it to start up properly and take me to the login page

**Screenshots**

![ui](https://github.com/exadel-inc/CompreFace/assets/25761276/fb7a402a-b999-4601-85de-a29d9d6e0ff0)

**Desktop (please complete the following information):**

 - OS: Ubuntu Server 23.10
 - Browser: Chrome
 - Version: 1.2.0

**Logs**

Run those commands and attach result to the ticket:

[docker_ps.txt](https://github.com/exadel-inc/CompreFace/files/15264286/docker_ps.txt)

[docker_compose_logs.txt](https://github.com/exadel-inc/CompreFace/files/15264289/docker_compose_logs.txt)

**Additional context**

The log is repeating `2024-05-09 15:32:25.272  INFO 7 --- [nio-8080-exec-1] o.s.s.o.p.token.store.JdbcTokenStore     : Failed to find access token` I've tried searching for that error but haven't found anything

**Comment by MOpenlander** [comment]
It just started working after several reboots

**Comment by saaruni1000** [comment]
@MOpenlander by "several reboots" you mean you just did "docker container restart compreface-admin" a few times until it started working?

**Comment by MOpenlander** [comment]
@saaruni1000 I think I rebooted the host machine a few times as well as restarting the Docker container a couple of times between reboots. This was a while ago so my memory is a bit fuzzy, but I remember it just started working for me after a bit.
