### ISSUE TITLE
好像无法连接

### ISSUE THREAD

**Issue by duxingxia081** [exadel-inc/CompreFace#327]
compreface-core           | detected number of CPU cores: 2
compreface-core           | current working directory: /app/ml
compreface-core           | detected binary path: /usr/local/bin/uwsgi
compreface-core           | setgid() to 33
compreface-core           | setuid() to 33
compreface-core           | your memory page size is 4096 bytes
compreface-core           | detected max file descriptor number: 1048576
compreface-core           | lock engine: pthread robust mutexes
compreface-core           | thunder lock: disabled (you can enable it with --thunder-lock)
compreface-core           | uwsgi socket 0 bound to TCP address 0.0.0.0:3000 fd 3
compreface-core           | Python version: 3.7.4 (default, Sep 12 2019, 15:40:15)  [GCC 8.3.0]
compreface-core           | Python main interpreter initialized at 0x555b5317b010
compreface-core           | python threads support enabled
compreface-core           | your server socket listen backlog is limited to 100 connections
compreface-core           | your mercy for graceful operations on workers is 60 seconds
compreface-core           | mapped 145840 bytes (142 KB) for 1 cores
compreface-core           | *** Operational MODE: single process ***
compreface-api            | Error: Could not find or load main class "-Xmx4g"
compreface-api            | Caused by: java.lang.ClassNotFoundException: "-Xmx4g"
compreface-api exited with code 1
compreface-admin          | Error: Could not find or load main class "-Xmx4g"
compreface-admin          | Caused by: java.lang.ClassNotFoundException: "-Xmx4g"
compreface-admin exited with code 1
compreface-ui             | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
compreface-ui             | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
compreface-ui             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
compreface-ui             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
compreface-ui             | 10-listen-on-ipv6-by-default.sh: /etc/nginx/conf.d/default.conf is not a file or does not exist, exiting
compreface-ui             | /docker-entrypoint.sh: Configuration complete; ready for start up
compreface-ui             | 2021/01/08 07:37:49 [emerg] 1#1: host not found in upstream "compreface-admin:8080" in /etc/nginx/conf.d/nginx.conf:2
compreface-ui             | nginx: [emerg] host not found in upstream "compreface-admin:8080" in /etc/nginx/conf.d/nginx.conf:2
compreface-ui exited with code 1
compreface-core           | WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x555b5317b010 pid: 1 (default app)
compreface-core           | *** uWSGI is running in multiple interpreter mode ***
compreface-core           | spawned uWSGI master process (pid: 1)
compreface-core           | spawned uWSGI worker 1 (pid: 15, cores: 1)

**Comment by pospielov** [comment]
Please recheck it, I fixed it in master branch in a5b2c5054c489f8094fdab288b6fa0a5d5ce269d commit

**Comment by pospielov** [comment]
@duxingxia081 We released new 0.4.1 version, could you check if your issue is still reproducible?
