### ISSUE TITLE
I'd like to use only face detection 

### ISSUE THREAD

**Issue by AndreyRoa** [exadel-inc/CompreFace#358]
I'd like to use the application only for the face detection, without the face recognition.
Can I do this?
If I can, how?

**Comment by pospielov** [comment]
You can create Face Collection and invoke recognition API without adding faces.
There won't be any errors and you will receive response in format like this:
```
{
  "result" : [ {
    "box" : {
      "probability" : 0.99964,
      "x_max" : 584,
      "y_max" : 521,
      "x_min" : 373,
      "y_min" : 286
    },
    "faces" : [ ]
  } ]
}
```
So you can easily use it for face detection only. 
The downside - the performance will be the same as it was for face recognition.
We are working on new Face Detection service that will show better performance as it will skip some stages of face recognition.
It will be in one of our new releases.

**Comment by pospielov** [comment]
Starting from 0.5.0 CompreFace supports face detection service.
