### ISSUE TITLE
How to restart clean?

### ISSUE THREAD

**Issue by oangelo** [exadel-inc/CompreFace#459]
I created a test user and now I want to start clean, but the older user is not deleted after "docker-compose down" or after removing the container. How can I start clean?

**Comment by pospielov** [comment]
Run docker command:
`docker volume ls`
Find volume with name `<folder_with_compreface_name>_postgres-data`
Probably it will be `compreface_041_postgres-data`
run: `docker volume rm compreface_041_postgres-data`

**Comment by oangelo** [comment]
Thanks.
