### ISSUE TITLE
Docker image missing (0.5.0-arcface-r100-gpu)

### ISSUE THREAD

**Issue by alekslyse** [exadel-inc/CompreFace#526]
Is the image 0.5.0-arcface-r100-gpu anywhere to be found? I followed the github config, but 0.5.0-arcface-r100-gpu seems to be missing from docker hub

**Comment by pospielov** [comment]
Hi, year, I marked this image as a work in progress as somehow we can't build it using our CI and push to prod. We will fix it in near future, but if you can try it out by building it by yourself. 
Just clone the repository, open the embedding-calculator folder, and run two commands:
`export VERSION=0.5.0`
`make build-images`
It will build all custom images locally

I'll return to this thread as soon as we fix our problem and publish 0.5.0-arcface-r100-gpu image on DockerHub

**Comment by pospielov** [comment]
I pushed `0.5.0-arcface-r100-gpu` image to DockerHub, should work now
