### ISSUE TITLE
UI - No route to host

### ISSUE THREAD

**Issue by Chreece** [exadel-inc/CompreFace#539]
**Describe the bug**
I'm getting an error when trying to login.

**To Reproduce**
1. Go to 'http://**compreface-ip**:8000'

**Expected behavior**
Get the login page

**Screenshots**
https://ibb.co/9Z8WKS1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 90

**Additional context**
Error logs:
`
[error] 23#23: *5 connect() failed (113: No route to host) while connecting to upstream, client: **laptop-ip**, server: ui, request: "GET /admin/user/me HTTP/1.1", upstream: "http://172.22.0.5:8080/user/me", host: "**compreface-ip**:8000", referrer: "http://**compreface-ip**:8000/"
`

**Comment by Chreece** [comment]
Tried: 
delete images-containers
docker prune

**Comment by pospielov** [comment]
Could you run `docker-compose logs` and share the output somewhere, e.g. pastebin? Or send it to our support email? 
Also, could you run `docker ps` and share the output?

**Comment by Chreece** [comment]
Logs:
https://pastebin.com/5DQQFVPj
docker ps:
https://pastebin.com/3cdsDMXc

**Comment by pospielov** [comment]
One of the containers doesn't run properly. 
It looks like that DB initialization wasn't successful.
Could you try this:
1. Run `docker volume ls`
2. Find a volume that probably named "compreface_050_postgres-data"
3. Run `docker volume rm compreface_050_postgres-data`
4. Try to run CompreFace again
5. Wait 1 minute before testing

**Comment by Chreece** [comment]
Done!
Thank you very much!
