### ISSUE TITLE
sign-up fails

### ISSUE THREAD

**Issue by QuanQuanoooooo** [exadel-inc/CompreFace#542]
**Describe the bug**
I followed the CompreFace/docs/How-to-Use-CompreFace.md and deployed with docker successfully. But when I begin to sign up an account, the page return
<img width="1038" alt="截屏2021-05-30 下午9 57 12" src="https://user-images.githubusercontent.com/33426645/120107060-0c427500-c192-11eb-85d8-99300df085f7.png">

**Desktop (please complete the following information):**
 - Linux
 - chrome
 - CompreFace_0.5.1

**Additional context**
docker ps
<img width="1142" alt="截屏2021-05-30 下午9 59 33" src="https://user-images.githubusercontent.com/33426645/120107121-5297d400-c192-11eb-8481-20ef0d750e63.png">
docker-compose up -d
[https://drive.google.com/file/d/1_8kNKcWVWXXIlNQRLG44-OKd34EvQ2S4/view?usp=sharing](url)

**Comment by QuanQuanoooooo** [comment]
CompreFace/java/admin/README.md describes "To open swagger api view follow http://localhost:8080/swagger-ui.html" But I cannot get the API specification on port 8080.

**Comment by pospielov** [comment]
It looks like compreface-admin node hasn't started properly.
Could you run `docker logs compreface-admin` and send the logs?
Also, you can try these steps:
https://github.com/exadel-inc/CompreFace/issues/539#issuecomment-846960264

We use Swagger internally, this is why this documentation is for those who run the admin module without everything else. If you run CompreFace with docker-compose, swagger will be available here:
http://localhost:8000/swagger/swagger-ui.html - for API endpoints
http://localhost:8000/admin/swagger-ui.html - for Admin endpoints
But as I mentioned - this is the internal features, so I'm not sure if it contains everything. 
The latest endpoint documentation is described here:
https://github.com/exadel-inc/CompreFace/blob/master/docs/Rest-API-description.md
