### ISSUE TITLE
Documentation for face plugins paramater.

### ISSUE THREAD

**Issue by tangopoint** [exadel-inc/CompreFace#562]
The API face plugin parameter is described in the documentation as `plugins`
https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md

According to the documentation here the parameter is `face_plugins`
https://exadel.com/news/compreface-version-0-5-is-live-heres-whats-new/

The proper parameter is `face_plugins`

**Comment by pospielov** [comment]
Thanks for finding the typo! I fixed them.
BTW if you would like to contribute, you can fork repository, fix such typos and create a pull request.
