### ISSUE TITLE
Connecting to a local host database

### ISSUE THREAD

**Issue by Ken-Sarowiwa** [exadel-inc/CompreFace#582]
I need and want to connect my localhost database, with this application. i am using the postgres as my database

**Comment by pospielov** [comment]
Please look at documentation that shows what you need to change to connect to your database:
https://github.com/exadel-inc/CompreFace/blob/master/docs/Architecture-and-scalability.md#postgresql
The problem you may face - if your database is in the same machine as CompreFace, you need to make it visible for CompreFace containers. If your postgres is in docker container you need to add it to the same network as CompreFace.
If it's not in docker, you can use "host.docker.internal" as a URL, read this answer for more info: 
https://stackoverflow.com/a/43541732

**Comment by Ken-Sarowiwa** [comment]
My postgres is actually in a docker container 
what do you mean i need to add it in the same network as compare face? Because i have specified the postgres username and password in the configuration file. how can i access the postgres web UI?. I tried accessing it using localhost://5432 but that didnt work.???

**Comment by Ken-Sarowiwa** [comment]
Should i install postgres in the directory as the compreFace project??

**Comment by pospielov** [comment]
To add your postgres to CompreFace network:
1. Run `docker network ls` command. Find the network name, I think to should be like `compreface_default`
2. When you start your postgres, run it with additional parameter `--network=compreface_default`
3. When you run your postgres, you need to set the name for container `--name=<some_name>`
4. Then in CompreFace config, you need to add the name of your postgres container as a domain, like `postgres_domain=<some_name>`

> how can i access the postgres web UI?. I tried accessing it using localhost://5432 but that didnt work.???
If you mean CompreFace postgres, then by default the port is closed for security reasons. To open it, you need to add:
```
ports:
      - "6432:5432"
```
to docker-compose file. Just look how it is done in dev version:
https://github.com/exadel-inc/CompreFace/blob/master/dev/docker-compose.yml
