### ISSUE TITLE
Admin login bug

### ISSUE THREAD

**Issue by Clinybug** [exadel-inc/CompreFace#588]
I can login as user but the system does not recognize admin email/password

To Reproduce on Debian Linux error
1. Fresh install of Docker 20.10.8 and Dockers-compose 1.29.2
2. Fresh install of CompreFace version 0.5.1
4. Menu does not have demo option anymore
5. Create login admin( 1rst time for admin )
6. Create login user
6. Login atempt from admin - error - "E-mail or Password is incorrect"
7. Login atempt from user - no error (but no option to create app)

**Desktop**
 - OS: Kali Linux Debian 64 bit 2021.1 amd64
 - Browser FireFox 78.7esr 64bit

**Comment by pospielov** [comment]
Hi, we will check the bug and fix it
Until then, you can just clear all the data and start it again. 
Just follow the instructions here:
https://github.com/exadel-inc/CompreFace/issues/459
Sorry for the inconvenience.

**Comment by Clinybug** [comment]
I have clear the data and tried few things, the issue might be comming from the capital letters in the email uppon creation.  If i reset the browser few times, the demo button tend to appear more often.  When the demo button appears and the email is not including any capital letters, the app works.

Hope this helps

**Comment by pospielov** [comment]
Thanks, we will try this too. We weren't able to reproduce it on our test environments. But we don't have the 0.5.1 version on test environments. Is it reproducible on 0.6.0?

**Comment by marcfielding1** [comment]
I'm sure you're aware of this, but just checking,  I find often when doing docker-compose up, I need to let it run through, let it pretend it's ready, kill it, up again, let all DB stuff run through for a few minutes and then try the UI. Otherwise it seems to get itself in a right pickle.

**Comment by pospielov** [comment]
ok, this is strange. 
It should run from the first time :)
Yes, you need to wait like 30 seconds until all servers will run. 
For me, the best way to understand it's ready is to run `docker-compose logs -f` command and wait until logs stop appearing

**Comment by marcfielding1** [comment]
Sure, I can reproduce it, it might be a separate issue to @Clinybug though if so I'll raise one, I was just mentioning it to be helpful as something to try :-)

**Comment by Clinybug** [comment]
I cannot reproduce the bug in V0.6.0, everything looks fine.

Le mar. 31 août 2021 à 13:43, Marc Fielding ***@***.***> a
écrit :

**Comment by marcfielding1** [comment]
Sorry this is on a totally fresh install I get that bug, apologies I didn't make that clear.

**Comment by Joey291** [comment]
i dont know why this is still a thing since 1 year. but it took me 4 hours to figure out the solution, for me was not to use any capital letters during the first registration.

**Comment by Larosen** [comment]
> i dont know why this is still a thing since 1 year. but it took me 4 hours to figure out the solution, for me was not to use any capital letters during the first registration.

THANK YOU SO MUCH!!!!!
This was finally the right solution, after I have removed the container and all settings probably 20 times completely and reloaded. Even my first and last name, as well as all letters in the password must be written in lower case so that I have admin rights after login and can see the demo app, as well as create my own applications.

**Comment by atv2016** [comment]
I am getting the same issue but in an iframe. Outside of the iframe it works fine. Maybe a caching issue or something.
