### ISSUE TITLE
Memory consumption when POSTing multiple face files to recognition service

### ISSUE THREAD

**Issue by Robert-IW** [exadel-inc/CompreFace#597]
**Describe the bug**
Requesting identities for each face in directory of multiple faces (> 500 jpgs with max size 100 kB) consumes RAM/Swap (16 GB/2GB) until container crashes. I've tried this with the python SDK, pycurl and curl with the same results.

**To Reproduce**
1. activate conda environment
2. docker-compose up -d
3. run bash script with curl looping through image directory

**Expected behavior**
return API request response for each image
clear cache/memory

**Screenshots**
![image](https://user-images.githubusercontent.com/12445426/133450836-64e0cb8f-3145-4427-bf71-2231e35608fb.png)
![image](https://user-images.githubusercontent.com/12445426/133451190-5ad26701-aaa9-41d5-8812-1eb0fd032436.png)

**Desktop (please complete the following information):**
- CompreFace version 0.6.0
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Docker version 20.10.8
 - docker-compose version 1.29.2

**Additional context**

**Comment by pospielov** [comment]
Hi Robert, sorry for the long reply.
I just tried your script on my folder with 1100 images(size of images mostly more than 100kb ) and got a very different result: 
![image](https://user-images.githubusercontent.com/3736126/133924708-58cb21e7-0f16-4fad-9668-69b96e38e957.png)
What I recommend here, try to change the limit for `compreface-api` container.
To do so, you need to open your `.env` file and change the value `compreface_api_java_options`, e.g.:
```compreface_api_java_options=-Xmx1g```
It will make Java work with a max of 2g memory consumption and run memory garbage collector more often.

**Comment by pospielov** [comment]
I made a mistake in the script, so there was no recognition...
here are the stats after I fixed it:
![2021-09-19_18-58](https://user-images.githubusercontent.com/3736126/133934231-e8b0e9cf-29c8-42c7-93eb-9f3efd03d8db.png)
SO basically I have even more memory consumption on `compreface-core`, but not so big on `compreface-api`.
The reason could be with the number of saved faces in face collection - I tested on one face. But it really depends on the number of faces. 
How many faces have you saved to face collection?

**Comment by Robert-IW** [comment]
Hi Posipielov
Thanks for your response. The .env change (Xmx8g to Xmx2g) solved the issue. I have just over 7000 images in the database.
![image](https://user-images.githubusercontent.com/12445426/133968799-0dac4314-0311-4159-9600-8385e92a6d34.png)

**Comment by pospielov** [comment]
Because of the tricky behavior of Java memory properties, when you set Xmx2g, expect that the maximum memory consumption of this container may be up to 4Gb.

**Comment by lkinfotechai** [comment]
how i can change the .env file after docker install. where to change
and how much maximum faces i can add in collection ?

**Comment by pospielov** [comment]
when you download CompreFace, there are two files in archive `docker-compose.yml` and `.env`.
So you need to change `.env` file
It should be changed before running `docker-compose up -d`
if you already run CompreFace, you need to stop it first with `docker-compose down`, then change `.env` file, and then run CompreFace again with `docker-compose up -d`
