### ISSUE TITLE
Cannot Start Postgres DB Container on windows server 2019

### ISSUE THREAD

**Issue by HarisMohre** [exadel-inc/CompreFace#598]
**Describe the bug**
Hi,

I recently setup a VM and i am trying to start the application on it using the build in Docker settings. So far everything is going good, but I am now facing an issue where the Postgres DB Container is not starting. I have attached the Compose Logs here too. If you can help me with this then it would be great.

[logs.txt](https://github.com/exadel-inc/CompreFace/files/7175356/logs.txt)

**To Reproduce**
1. Setup Docker on Windows Server 2019
2. Download Compreface 0.6.x
3. Go to the folder
4. Run docker-compose up -d.
5. After that , run docker-compose logs

**Expected behavior**
- Shall Be able to get to Login Screen and create a user.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser : Google Chrome
 - Version Compfreface 0.6.x

**Additional context**
![Error](https://user-images.githubusercontent.com/89574723/133563097-b1f5b24b-8924-49bd-91e4-9de683c1cd8f.jpg)

It Says in the Logs that the connection attempt Failed. Maybe That might help. It does look like the Postgre DB didnt start.

**Comment by pospielov** [comment]
Hi, sorry for the long reply.
I don't have any experience with Windows Server 2019.
CompreFace uses the default image of PostgreSQL, so I recommend finding a tutorial on how to run PostgreSQL in docker on Windows Server 2019. As soon as you will manage to run clean PostgreSQL, I believe the CompreFace version also will work.
Also, to check the Postgres logs, run `docker logs compreface-postgres-db`.

**Comment by HarisMohre** [comment]
Hey Bro, No issues... I can understand this might be an issue as Windows Server comes built in with Docker support but for some reason , it`s not working. It`s okay though as I have asked My Infra team to setup a LINUX VM instead. 

So yeah, all good for now.
