### ISSUE TITLE
Add query parameter to "List of All Saved Examples of the Subject" endpoint

### ISSUE THREAD

**Issue by pospielov** [exadel-inc/CompreFace#608]
https://github.com/exadel-inc/CompreFace/blob/master/docs/Rest-API-description.md#list-of-all-saved-examples-of-the-subject

Right now this endpoint returns all subject examples. We need to add the query parameter "subject" to return examples of this subject.

e.g. we have such subject examples:

```json
[
    {
      "image_id": 1,
      "subject": "John"
    },{
      "image_id": 2,
      "subject": "John"
    },{
      "image_id": 3,
      "subject": "Jane"
    }
]
```
With this request:
```http://localhost:8000/api/v1/recognition/faces?subject=John```
It should return such response:
```json
{
  "faces": [ 
    { "image_id": 1, "subject": "John" },
    { "image_id": 2, "subject": "John" }
  ],
  "page_number": 0,
  "page_size": 10,
  "total_pages": 1,
  "total_elements": 2
}
```

**Comment by deepto98** [comment]
@pospielov  I'd like to work on this issue, can you assign this to me? Also if possible, can you point me to the controller where the API logic is defined?

**Comment by pospielov** [comment]
Hi, thanks for the interest in our repository, I assigned the issue to you
https://github.com/exadel-inc/CompreFace/blob/master/java/api/src/main/java/com/exadel/frs/core/trainservice/controller/EmbeddingController.java#L102
Here is the line where you should start the investigation.
