### ISSUE TITLE
Login page not loading

### ISSUE THREAD

**Issue by spro300** [exadel-inc/CompreFace#611]
Hi,

I was able to successfully download and run the docker-compose.yml file for compreface. However, I had to change the port from 8000 to 6000 since I have portainer running on the same environment and there was a port conflict. The compreface stack starts successfully. However, I cannot access http://local-ip:6000/login. It doesn't return a website. Is running on port 8000 a must?

Thanks

**Comment by spro300** [comment]
I forgot to attach pictures of the docker-compose.yml file. 
<img width="1435" alt="Screen Shot 2021-10-01 at 1 12 56 PM" src="https://user-images.githubusercontent.com/84641622/135667777-0fb4e108-1dba-4dab-8c7d-3934c048fe6e.png">
<img width="1437" alt="Screen Shot 2021-10-01 at 1 13 23 PM" src="https://user-images.githubusercontent.com/84641622/135667785-48896595-fff0-4e94-8dc6-e1351052a428.png">

**Comment by pospielov** [comment]
Hi, no, you can choose the port you like.
The problem here is with the browser. E.g. here is a list of ports Google Chrome doesn't want to work:
https://superuser.com/a/188070
And 6000 is one of them. Just choose another port, 6001 works for me :)

**Comment by spro300** [comment]
Ah works perfect now. Thanks alot!
