### ISSUE TITLE
Input is not in focus when you create new Application

### ISSUE THREAD

**Issue by pospielov** [exadel-inc/CompreFace#613]
**Describe the bug**
After opening the New Application window, the Application Name field isn't active and does not allow you to enter characters without first clicking the mouse.

**To Reproduce**
Preconditions:
1. User has an active account as OWNER in the CompreFace
Steps:
1. Log in to the application as OWNER
2. In the APPLICATIONS section click the Create New button

Actual result:
The App Name field isn't active in the Create Application window opens 

**Expected behavior**
The App Name field is active and allows you to type the characters

**Screenshots**
![image](https://user-images.githubusercontent.com/3736126/135712673-febddff8-fec0-48cd-a2e5-35b7ce1e469a.png)

**Comment by durgeshmeena** [comment]
@pospielov 
I have already worked on it, Please assign this issue to me

**Comment by pospielov** [comment]
Closed by https://github.com/exadel-inc/CompreFace/pull/625
