### ISSUE TITLE
Input is not in focus when you create new Service

### ISSUE THREAD

**Issue by pospielov** [exadel-inc/CompreFace#614]
**Describe the bug**
The Name field in the Create Service window isn't active and does not allow you to enter characters without first clicking the mouse

**To Reproduce**
Preconditions:
1. User has an active account in the CompreFace
2. User has access to any application within CompreFace

Steps:
1. Log in to the application
2. In the APPLICATIONS section create a new application or use as existing one
3. Open some application
4. In the Services section click the Create New button

Actual result:
The Name field isn't active in the Create Service window opens 

**Expected behavior**
The Name field is active and allows you type the characters without first clicking the mouse in this field

**Screenshots**
![image](https://user-images.githubusercontent.com/3736126/135712786-d62c5040-c91c-43e3-bd3f-29590df95eb8.png)

**Comment by durgeshmeena** [comment]
@pospielov 
I want to work on this issue, Please assign this to me

**Comment by pospielov** [comment]
Hi, thanks for the interest in our repository, I assigned the issue to you
Our Javascript expert is on vacation until October 5, so he will look at it a little bit later. I'll check the functionality tomorrow.

**Comment by pospielov** [comment]
Closed by https://github.com/exadel-inc/CompreFace/pull/624
