### ISSUE TITLE
Add tooltips to the buttons on the CompreFace page

### ISSUE THREAD

**Issue by pospielov** [exadel-inc/CompreFace#615]
Preconditions:
1. User has an active account in the CompreFace
2. User has access to any application within CompreFace

Steps:
1. Log in to the CompreFace
2. In the APPLICATIONS section create a new application or use as existing one
3. Open some application
4. In the Services section create a new service or use as existing one 
5. Click the "Test" button on any service
6. Uploaded the some picture to the CompreFace
7. There are three buttons to the left of the picture, place the mouse cursor on any of these buttons

Expected result:
Button tooltip appears. From left to right button tooltips have to are: "Upload new image", "Clear results", "Show landmarks".

![image](https://user-images.githubusercontent.com/3736126/135712859-53d6e862-5c2c-4fa6-841a-0f5e156056ae.png)

**Comment by durgeshmeena** [comment]
@pospielov 
I have already worked on it, Please assign this issue to me 
Also, review my PL
