### ISSUE TITLE
Add Validation on empty subject when saving a subject example

### ISSUE THREAD

**Issue by pospielov** [exadel-inc/CompreFace#617]
**Describe the bug**
There is a possibility to save a Subject Example with empty subject name

**To Reproduce**
Preconditions:
1. User has an active account and application
2. The app has a recognition service

Steps:
1. Save a Subject Example with an empty subject name using this rest API request:
https://github.com/exadel-inc/CompreFace/blob/master/docs/Rest-API-description.md

Actual result: the example is successfully saved with an empty name

**Expected behavior**
Validation should apply. The error should be displayed
Error message:
"Subject name is empty"

**Screenshots**
![image](https://user-images.githubusercontent.com/3736126/135713529-36783781-9e1a-4eed-a98b-b69e4cb8a63f.png)

**Comment by mslowiak** [comment]
Hi @pospielov!
Can I dig into that issue? :)

**Comment by pospielov** [comment]
Hi, thanks for the interest in our repository, of course, you can, I assigned the issue to you

**Comment by mslowiak** [comment]
@pospielov 
Is the postman collection available somewhere?
If not, could you export the request that is provided in the ticket?

**Comment by mslowiak** [comment]
I tested it running the requests from Intellij :) PR is ready for a review

**Comment by pospielov** [comment]
Hi, sorry for the long response, thanks for the pull request, the code looks correct, but I'll check how it works tomorrow and merge if everything fine
