### ISSUE TITLE
FATAL:  database "frs" does not exist

### ISSUE THREAD

**Issue by weitheng** [exadel-inc/CompreFace#650]
**Describe the bug**
Getting this `FATAL:  database "frs" does not exist` when trying run using docker-compose. The error seems to be originating from the Postgres database. I must have set up the docker-compose file incorrectly.

**To Reproduce**
https://pastebin.com/xWpPDuKM

**Comment by pospielov** [comment]
please look at the original docker-compose file, there are three variables that define the credentials and the database name:
      - postgres_username
      - postgres_password
      - postgres_db
Using those variables we help to:
1. Understand Postgres how to initialize
2. Understand admin and API nodes to connect to Postgres
So, you need to set these three environment variables for `compreface-postgres-db`:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
And these three environment variables for `compreface-admin` and `compreface-api`:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_URL

But what was the original reason to change the default `docker-compose` file? Probably we can start from it and change the points you want

**Comment by weitheng** [comment]
Thanks for the suggestions and advice! I have included back the environment variables needed and it works now! Thank you :)

**Comment by abuelgasimsaadeldin** [comment]
Hi @pospielov @weitheng,

I am receiving the same error message when trying to connect to my Docker Postgres DB using DBeaver. Below is a snapshot of my environment variables and the DBeaver configuration. 

**Environment variables:**

![image](https://user-images.githubusercontent.com/68045710/203214026-652757a3-2582-4f05-a149-274bc32f2627.png)

**DBeaver Configuration:**

![image](https://user-images.githubusercontent.com/68045710/203213309-d0023189-4ac2-4715-ac3b-d113ed73624f.png)

I've ensured that the Docker container is running using the command ```docker-compose up -d```. I would really appreciate your help.

Regards,
Abu

**Comment by pospielov** [comment]
As I understand, you are trying to connect the default CompreFace database from the docker-compose configuration.
If this is the case, by default, the port to DB is closed because of security reasons. 
You need to change docker-compose configuration to open it.
Please look at the development docker-compose file on how the port is opened:
https://github.com/exadel-inc/CompreFace/blob/master/dev/docker-compose.yml
