### ISSUE TITLE
Deploying Compreface on an Android device

### ISSUE THREAD

**Issue by AnkurChatter** [exadel-inc/CompreFace#656]
Hi,

We were thinking of deploying CompreFace on Android Devices and based on our research, deploying docker containers on Android platforms is not very straight forward.
I know there are **mobile net custom builds**_(which requires less processing power)_ that can be used for such purposes, just wanted to ask if this is a scenario which has been tested and what was the inference ?

If not tested, what is your recommendation and how do we go about it.

Thank You.

**Comment by pospielov** [comment]
Hi,

There is no possibility to run CompreFace on Android devices. 
First of all, I don't think there is an easy way to run docker on Android at all. Android is not on the list of supported systems for Docker engine.
Also, CompreFace doesn't support ARM devices.
Mobile net custom builds just use neural networks with small architectures, so it runs faster on slow devices (including mobile). 
If you need face recognition on Android I recommend running CompreFace somewhere else and making rest requests from the android devices for recognition.

**Comment by AnkurChatter** [comment]
Yeah I had the same thought, thank you for the confirmation.
