### ISSUE TITLE
1.Can I update an image by Image_id?

### ISSUE THREAD

**Issue by dahvlhldle** [exadel-inc/CompreFace#661]
Thank you very much for your contribution.
1.Can I update an image by Image_id?
2.Is it possible to specify image_id when an example is uploaded?

**Comment by pospielov** [comment]
Hi, no both operations are impossible. 
If you need to replace the image - you just delete it and upload a new one.
Could you tell more about the case where operations your mentioned are useful?

**Comment by dahvlhldle** [comment]
I want to replace the image ID with the user ID, so you don't have to store all the relationships between them.

> Hi, no both operations are impossible. If you need to replace the image - you just delete it and upload a new one. Could you tell more about the case where operations your mentioned are useful?

I want to replace the image ID with the user ID, so i don't have to store  the relationships between them.
