### ISSUE TITLE
How can I remove the 5MB upload limit

### ISSUE THREAD

**Issue by cheng-orange** [exadel-inc/CompreFace#680]

**Comment by pospielov** [comment]
The limit is defined in nginx config.
You can find the default config here:
https://github.com/exadel-inc/CompreFace/blob/master/ui/nginx/conf.d/nginx.conf
see the line `client_max_body_size 5000K;`
You can replace this config without building a new version of CompreFace.
All you need is to create a volume for `compreface-core` container in `docker-compose` file. The path inside the container is "/etc/nginx/conf.d"
Then you will need to place in this volume your own nginx config.

**Comment by nvkhiem** [comment]
Hi @pospielov,
I configured `client_max_body_size` to 50M but not success. I got <Response [413]> (413 = payload too large) when recognizing images above 5MB size. I tried with both normal and mobile builds.
Do you have any ideas?

P/s: I'm sure that I changed this config by use this command: 'docker cp compreface-core:/etc/nginx/conf.d C:\nginx' and then check the file C:\nginx\nginx.conf that having line `client_max_body_size 50M;`
Thanks,

**Comment by pospielov** [comment]
Hi, does the error is the same as before you changed the config? 
Could you try to break that `nginx.conf` somehow and check that CompreFace stopped working at all?

**Comment by nvkhiem** [comment]
Hi @pospielov, the error is the same as before. I recognized that this change should apply for compreface-ui but not compreface-core. It's ok after apply your fix for compreface-ui.
Thanks for your support.

**Comment by pospielov** [comment]
Bad news, looks like it is hardcoded in `application.yml` with 10Mb value:
https://github.com/exadel-inc/CompreFace/blob/master/java/api/src/main/resources/application.yml
For now you can only change it and rebuild CompreFace. I'll create a task to make it dynamic

**Comment by nvkhiem** [comment]
I fixed this problem by follow steps:
    1. Edit file nginx.conf: Set client_max_body_size 50M;
    2. Edit file docker-compose.yml, add volumes to compreface-core:
            volumes:
                - nginx_conf_volume:/etc/nginx/conf.d
            nginx_conf_volume should be also declared on top of file:
            volumes:
                - nginx_conf_volume:
    3. Run command: docker-compose up
    4. Copy nginx.conf: docker cp /path/to/nginx.conf compreface-ui:/etc/nginx/conf.d
    5. Restart compose.

**Comment by mykeehu** [comment]
How can I change limit under Windows?

**Comment by mykeehu** [comment]
Under Windows, how can I change the limit on Docker Desktop?
