### ISSUE TITLE
504 gateway time out

### ISSUE THREAD

**Issue by ersaurabh101** [exadel-inc/CompreFace#764]
I have created a VM instance in google cloud. It is 2core 4gb. Most of the time, it is giving this error of time out.

We are trying to match the face from base64 image. Please advise what is the best practice to avoid this error.

Attaching image for reference
![image](https://user-images.githubusercontent.com/50316624/162602652-cad46723-2535-4b21-83a9-cc7c9bcb4059.png)

Best Regards

**Comment by pospielov** [comment]
Could you send the logs from the `docker-compose logs` command?

**Comment by ersaurabh101** [comment]
Attaching all the logs for your reference. We are unable to use this instance since we created it 8 days ago. Please clearly mention minimum requirement for the same, it will surely help others in future.

these are logs from compreface-api, trying to show last 500 lines
![WhatsApp Image 2022-04-15 at 2 29 16 PM](https://user-images.githubusercontent.com/50316624/163558336-fd023b71-a1ea-4b93-8009-30098524c9f9.jpeg)
![WhatsApp Image 2022-04-15 at 2 28 31 PM](https://user-images.githubusercontent.com/50316624/163558338-8946d06a-cb3a-4e5b-8846-d060b107ffec.jpeg)
![WhatsApp Image 2022-04-15 at 2 27 41 PM](https://user-images.githubusercontent.com/50316624/163558343-0d1855a3-5bd2-49e0-a1fa-e5521dacd5a2.jpeg)
![WhatsApp Image 2022-04-15 at 2 30 25 PM](https://user-images.githubusercontent.com/50316624/163558334-5c807fed-083d-4695-a96c-013bfa458832.jpeg)

![WhatsApp Image 2022-04-15 at 2 26 38 PM](https://user-images.githubusercontent.com/50316624/163558308-dcc3ee81-3ecc-4c20-9c86-18cee17cdb0f.jpeg)
![WhatsApp Image 2022-04-15 at 2 25 57 PM](https://user-images.githubusercontent.com/50316624/163558314-a73c9c29-276e-4b00-a420-ce2a5ca5d47d.jpeg)
![WhatsApp Image 2022-04-15 at 2 25 17 PM](https://user-images.githubusercontent.com/50316624/163558319-55b2ac2a-1791-47d5-9c27-2e1dd073c6b2.jpeg)
![WhatsApp Image 2022-04-15 at 2 24 35 PM](https://user-images.githubusercontent.com/50316624/163558322-c78ff5cb-93ee-41bb-a80d-1cd80e04cce4.jpeg)
![WhatsApp Image 2022-04-15 at 2 23 49 PM](https://user-images.githubusercontent.com/50316624/163558324-c0f80742-eb1d-4cc6-81b4-c65dd1d5f4a5.jpeg)
![WhatsApp Image 2022-04-15 at 2 22 53 PM](https://user-images.githubusercontent.com/50316624/163558325-607bc8b3-9288-4136-b6d3-ce5485be9335.jpeg)
![WhatsApp Image 2022-04-15 at 2 21 54 PM](https://user-images.githubusercontent.com/50316624/163558326-f67accce-3714-40c3-8436-9fd159d7257e.jpeg)
![WhatsApp Image 2022-04-15 at 2 31 45 PM](https://user-images.githubusercontent.com/50316624/163558328-f0780265-0a25-45e0-8714-cd0c81a9a666.jpeg)
![WhatsApp Image 2022-04-15 at 2 31 00 PM](https://user-images.githubusercontent.com/50316624/163558332-4e60c4bb-d2fb-48b7-8cc6-0b47556bc13c.jpeg)

**Comment by pospielov** [comment]
You send logs only from `compreface-api` node. Could you send logs from `compreface-core` logs?
If it's not working then probably you need more RAM. For 5000 faces probably you need about 8-10 Gb of RAM.
The number of matches per second depends on the size of the input image and number of faces on it.
To increase number of matches per second you can:
1. Use GPU instance
2. Add more compreface-api and compreface-core instances. 
3. Use a more powerful CPU instance.

**Comment by ersaurabh101** [comment]
Thank you for your reply. I am upgrading my server now.
