### ISSUE TITLE
ERROR: pull access denied for exadel/compreface-postgres-db

### ISSUE THREAD

**Issue by Ahmedsaber9** [exadel-inc/CompreFace#798]
**Describe the bug**
ERROR: pull access denied for exadel/compreface-postgres-db
after trying to use docker-compose up -d at the project dir.

**To Reproduce**
1. Wget the last master.zip
2. unzip the file
3. go to the unzipped file dir
4. use the command "docker-compose up -d"

**Expected behavior**
installed successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/23035531/175797699-5ab11ef7-cd00-4cf1-9d0f-7926249e669c.png)

 - OS: [Ubuntu 18.04]
 - Doker Version [Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:56 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:02 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0]

Thanks.

**Comment by Ahmedsaber9** [comment]
Any help ?

**Comment by Ahmedsaber9** [comment]
@pospielov

**Comment by Ahmedsaber9** [comment]
resolved by using that docs 

https://github.com/exadel-inc/CompreFace/releases/tag/v1.0.0

**Comment by Ahmedsaber9** [comment]
resolved by using those docs

https://github.com/exadel-inc/CompreFace/releases/tag/v1.0.0

**Comment by Ahmedsaber9** [comment]
For me I have no idea if it can help.
If you need my help at any testing case I'm available.

**Comment by pospielov** [comment]
My point is that in all our guides we say to download the zip archive from `releases`:
https://github.com/exadel-inc/CompreFace#getting-started-with-compreface
https://github.com/exadel-inc/CompreFace/releases/tag/v1.0.0
But you still cloned the repository. I just want to understand what can we do to avoid unnecessary cloning repository.

**Comment by Ahmedsaber9** [comment]
Yes, I'm sorry it's my fault, by nature I do the clone, and I did a wrong assumption, that I don't need to open that URL and download the release zip.
You could add "Don't clone the master" or something like that, from my point of view.
Thanks.
