### ISSUE TITLE
Return more than one face

### ISSUE THREAD

**Issue by MuhmdHsn313** [exadel-inc/CompreFace#801]
Hello

I want to return all similar faces to the comparison face.

Thanks...

**Comment by MuhmdHsn313** [comment]
@pospielov Could you provide me a sample code?
Thanks

**Comment by pospielov** [comment]
https://github.com/exadel-inc/compreface-javascript-sdk/tree/main/face_founder_demo
we have a demo in our JavaScript SDK with similar functionality

**Comment by martinenkoEduard** [comment]
Is there a way to set a threshhlod on similarity and number of faces?

**Comment by MuhmdHsn313** [comment]
I found the result using Postman

For others, you can use RestAPI with Postman and get the result.

Request URL:
```
{{compreface_base_url}}/api/v1/recognition/recognize?prediction_count=10
```
Body:
```
file: multi-part file contain the faces.
```

See the postman collection for more:
https://documenter.getpostman.com/view/17578263/UUxzAnde
