### ISSUE TITLE
local build does not work cause lombok

### ISSUE THREAD

**Issue by leccyril** [exadel-inc/CompreFace#826]
**Describe the bug**
Project could not build because lombox make an issue

**To Reproduce**
mvn install of the java project with for example java18 or 11

**Expected behavior**
Build have to work

you can use last version of lombok where fix is done

        <lombok.version>1.18.12</lombok.version>
to
        <lombok.version>1.18.22</lombok.version>

in java project pom.xml

**Comment by VolodymyrBushko** [comment]
The master branch should build. Are you sure that you use Java 11?

There could be non-compatibilities between Java's latest versions and Lombok 1.18.12.

Try to keep all dependencies as they are on the master branch and make sure that the project's Java version is 11.
