### ISSUE TITLE
incompatible types: com.exadel.frs.core.trainservice.dto.FindFacesResultDto cannot be converted to com.exadel.frs.core.trainservice.dto.FacePredictionResultDto

### ISSUE THREAD

**Issue by leccyril** [exadel-inc/CompreFace#828]
**Describe the bug**
incompatible types: com.exadel.frs.core.trainservice.dto.FindFacesResultDto cannot be converted to com.exadel.frs.core.trainservice.dto.FacePredictionResultDto

error occurs when we want to build the java project on this class : FacesMapperImpl

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project frs-core-app: Compilation failure
[ERROR] /workspace/compreface/api/target/generated-sources/annotations/com/exadel/frs/core/trainservice/mapper/FacesMapperImpl.java:[250,45] incompatible types: com.exadel.frs.core.trainservice.dto.FindFacesResultDto cannot be converted to com.exadel.frs.core.trainservice.dto.FacePredictionResultDto

it seems the map structur automatic mapper is not working  

**To Reproduce**

clone  master branch and try to build java project

java 11 or java 18

**Expected behavior**
Build works

**Comment by VolodymyrBushko** [comment]
Are you sure that versions of your dependencies are the same as on the master branch?

There could be non-compatibilities between dependencies.

For example, late versions of Lombok might be non-compatible with old versions of Mapstruct.

**Comment by leccyril** [comment]
i took master branch , then build with java 11 , api not building

`/home/cyril.xxxx/.jdks/liberica-11.0.15.1/bin/java -Dmaven.multiModuleProjectDirectory=/home/cyril.xxxx/dev/projects/facial recognition/source/CompreFace/java/api -Dmaven.home=/home/cyril.xxxx/dev/environment/idea-IU-213.7172.25/plugins/maven/lib/maven3 -Dclassworlds.conf=/home/cyril.xxxx/dev/environment/idea-IU-213.7172.25/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/home/cyril.xxx/dev/environment/idea-IU-213.7172.25/plugins/maven/lib/maven-event-listener.jar -javaagent:/home/cyril.xxxx/dev/environment/idea-IU-213.7172.25/lib/idea_rt.jar=38841:/home/cyril.xxx/dev/environment/idea-IU-213.7172.25/bin -Dfile.encoding=UTF-8 -classpath /home/cyril.xxxx/dev/environment/idea-IU-213.7172.25/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar:/home/cyril.xxxx/dev/environment/idea-IU-213.7172.25/plugins/maven/lib/maven3/boot/plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3.3 install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.exadel:frs-core-app:jar:0.0.1-SNAPSHOT
[WARNING] The expression ${parent.version} is deprecated. Please use ${project.parent.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ----------------------< com.exadel:frs-core-app >-----------------------
[INFO] Building frs-core-app 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ frs-core-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ frs-core-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 71 source files to /home/cyril.xxxx/dev/projects/facial recognition/source/CompreFace/java/api/target/classes
[INFO] /home/cyril.xxxx/dev/projects/facial recognition/source/CompreFace/java/api/src/main/java/com/exadel/frs/core/trainservice/system/swagger/SwaggerInfoProperties.java: Some input files use or override a deprecated API.
[INFO] /home/cyril.xxxx/dev/projects/facial recognition/source/CompreFace/java/api/src/main/java/com/exadel/frs/core/trainservice/system/swagger/SwaggerInfoProperties.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/cyril.xxx/dev/projects/facial recognition/source/CompreFace/java/api/target/generated-sources/annotations/com/exadel/frs/core/trainservice/mapper/FacesMapperImpl.java:[245,45] incompatible types: com.exadel.frs.core.trainservice.dto.FindFacesResultDto cannot be converted to com.exadel.frs.core.trainservice.dto.FacePredictionResultDto
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.359 s
[INFO] Finished at: 2022-07-13T13:10:06+04:00
`

**Comment by leccyril** [comment]
for information for admin project i updated all depenencies with last version and project is working "just to test"

**Comment by leccyril** [comment]
i launched from intellij java folder or api folder it is the same error, i have java18 installed and only on intellij i can switch easily java version.

I f i launch on terminal command directly it is java 18 used

**Comment by VolodymyrBushko** [comment]
You can try to reimport all dependencies and try to build the project again.

**Comment by VolodymyrBushko** [comment]
I can reproduce the problem. It occurs for me when I change the Lombok version from 1.18.12 to 1.18.22 in root pom.xml (I'm using java 11).

**Comment by pospielov** [comment]
I tried to build the project with the same Java and it works too.
Here is the log: [log.txt](https://github.com/exadel-inc/CompreFace/files/9104380/log.txt)
It looks like you are trying to build the project from `java/api` folder. 
You need to build it from `java` folder

**Comment by leccyril** [comment]
it seems to be this, first java11 was not yet installed when i done test
