### ISSUE TITLE
old version of maven dependencies in java project

### ISSUE THREAD

**Issue by leccyril** [exadel-inc/CompreFace#832]
**Describe the bug**
Version of maven dependencies are quite old : example lombok, mapstruct etc...

**To Reproduce**
check on maven repository last version of dependencies

**Expected behavior**
Have last version of maven dependencies

**Comment by pospielov** [comment]
I asked our Java dev to update project dependencies. So it will be in the new 1.1 release (master branch)

**Comment by leccyril** [comment]
Hello OK great Thanks i am thinking how to use on my project (i manage to use all containers locally ! Because admin will not fit with our requirementSo i think i will embbed database schéma on our dbDelete admin and ui (and use New admin code from our app (just add services finally) Just let api an common launcher on docker... Because api can be call with api key... And services will be created once... But admin Authentication is complicatedI saw Java code from common is using your specific SDK ? Because at the end we can code the api and common no ? Or your code is using ai algorithm ? Like face net etcI would like for example an explanatation of your added as layer , what your team did exactly and what can be done by us if we want to see your dev projet to fit with oursYou made à great job and i am sur i can make ligther what i need at the end ^^Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Pospielov Serhii ***@***.***> Date : 13/07/2022  20:58  (GMT+04:00) À : exadel-inc/CompreFace ***@***.***> Cc : leccyril ***@***.***>, Author ***@***.***> Objet : Re: [exadel-inc/CompreFace] old version of maven dependencies in java project (Issue #832) 
I asked our Java dev to update project dependencies. So it will be in the new 1.1 release (master branch)
