### ISSUE TITLE
Sometimes getting low result value of face verification

### ISSUE THREAD

**Issue by Vladimir-v1** [exadel-inc/CompreFace#845]
Hi, 

Firstly thank you so much for this great solution!

I'm using custom build "SubCenter-ArcFace-r100-gpu", it works good and fast on my GTX 1080. I'm using only face verification by REST API between only two faces(each image with single face) and sometimes getting low value of comparation. When I got low value, next I'm checking same images in web UI(:8000 port) result of web UI checking is that what I'm expecting, value of comparation is ok. Would be great, if you can tell me please, how I can find this issue

For example, for same two faces(same images):
REST_API - 
  "result" : [ {
    "source_image_face" : {
      "box" : {
        "probability" : 0.99937,
        "x_max" : 481,
        "y_max" : 592,
        "x_min" : 278,
        "y_min" : 289
      }
    },
    "face_matches" : [ {
      "box" : {
        "probability" : 0.99809,
        "x_max" : 203,
        "y_max" : 262,
        "x_min" : 40,
        "y_min" : 43
      },
      "similarity" : 0.32197
    } ]
  } ]
}

WEB_UI -  
{
  "result": [ {
      "source_image_face": {
        "age": {
          "probability": 1,
          "high": 36,
          "low": 36
        },
        "gender": {
          "probability": 1,
          "value": "male"
        },
        "box": {
          "probability": 0.99955,
          "x_max": 403,
          "y_max": 650,
          "x_min": 212,
          "y_min": 407
        },
        "landmarks": [ [ 256,
            502 ],
          [ 346,
            501 ],
          [ 297,
            560 ],
          [ 266,
            590 ],
          [ 341,
            589 ] ]
      },
      "face_matches": [ {
          "age": {
            "probability": 1,
            "high": 33,
            "low": 33
          },
          "gender": {
            "probability": 1,
            "value": "male"
          },
          "box": {
            "probability": 0.99809,
            "x_max": 203,
            "y_max": 262,
            "x_min": 40,
            "y_min": 43
          },
          "landmarks": [ [ 86,
              129 ],
            [ 161,
              130 ],
            [ 124,
              168 ],
            [ 93,
              208 ],
            [ 151,
              209 ] ],
          "similarity": 0.98878
        } ]
    } ]
}

**Comment by pospielov** [comment]
I took your responses, cleaned the web UI from unnecessary data, and compared the responses:
![image](https://user-images.githubusercontent.com/3736126/180792238-d3720636-c0a6-4835-a817-a54e9ed3ac7c.png)
It looks like you use the same target image, but different source images.

**Comment by Vladimir-v1** [comment]
Thank you so much @pospielov!

Problem is solved!
