### ISSUE TITLE
No Login Controller 

### ISSUE THREAD

**Issue by Arab04** [exadel-inc/CompreFace#878]
Hi, I have installed compreFace locally and I created user but there is no login controller at all, Do I have to create it by myself because I want to create an app and get ApiKey but it requires jwt token if I am not mistaken because it says oops something went wrong

**Comment by Arab04** [comment]
I do not need web camera I only want to use endpoints and send photos through api

**Comment by Arab04** [comment]
or what should I do after registration of user ? which api should I use in order to get apikey I have read documentation but it wasn't clear for me

**Comment by pospielov** [comment]
Hi, do you use UI or REST API?
By default, we expect users will use UI for creating apps.

> if I am not mistaken because it says oops something went wrong"

Could you send me logs? it's `docker-compose logs` command

**Comment by Arab04** [comment]
Hi, I have solved yesterdays issue by making some changes

**Comment by Arab04** [comment]
yeah I use REST API, because I want to use it for mobile app, so do I have to make login controller which returns jwt token? because it is checking everywhere userId.

**Comment by Arab04** [comment]
Also could you please explain which steps do I have to take in order to get right apiKey, I mean 
step 1. register user through user REST API
step 2. create app using app REST API
step3. create module ..... staff like that

**Comment by Arab04** [comment]
Next issue is 
{
    "message": "Error during synchronization between servers: compreface-core executing POST http://compreface-core:3000/find_faces",
    "code": 41
}

**Comment by pospielov** [comment]
Tensorflow doesn't support ARM devices by default. This is why you didn't manage to install it on the M1 processor. There are workarounds, but I am afraid there are other not supported libraries as well. See this thread - https://github.com/exadel-inc/CompreFace/issues/610.

What is the problem when you install uWSGI on Windows?
