### ISSUE TITLE
extend the backend custom field and api

### ISSUE THREAD

**Issue by neonleo** [exadel-inc/CompreFace#934]
The UI current provide a key associate a subject, is it possible extend the field like person name as well as return the person name when return recognize result?

**Comment by pospielov** [comment]
I didn't get what do you mean.
Could you provide an example of the REST endpoint you want to extend, and how do you see the response?

**Comment by pospielov** [comment]
My best practice advice would be to store all personal information in an external system.
And then link the external id with CompreFace subject_id.
It will be easier to comply with legal regulations like GDPR, as you won't store any sensitive information in CompreFace, all info will be anonymized. 

But if you still want to store more info for functional reasons, the only workaround I can suggest is to put all info in subject_id, e.g., subject id will be "first_name.last_name"
