### ISSUE TITLE
Always detects unfamiliar people as someone i've trained

### ISSUE THREAD

**Issue by dodgeboy** [exadel-inc/CompreFace#950]
Face recognition is working great for me, with one huge exception.  It detects everyone (package delivery people, mail man, etc.) as one of the faces I've trained.  Even if the person looks nothing like one of the trained subjects, it seems to pick the closest one and match it.  Is there a way to configure it so that unknown people don't match as one of the subjects I've trained?

**Comment by pospielov** [comment]
All machine learning systems work in a way where it predicts one of the known classes with a certain probability. 
The idea here is the same - we always return the closest match, but we return the similarity with it, so you need to decide if it's big enough to trust. Here you can find considerations of how to choose this threshold: 
https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-Recognition-Similarity-Threshold.md

**Comment by abuelgasimsaadeldin** [comment]
Hi @pospielov,

May I ask from where I can adjust the setting to display only tags on faces above a certain similarity threshold on the ```compreface_webcam_recognition_demo.py``` application?

I assumed that by adjusting the following "det_prob_threshold" variable it would work, but apparently it is still showing tags on faces with similarity values lower than set threshold.

![pic](https://user-images.githubusercontent.com/68045710/203211538-423b5739-be46-4be0-bd8d-b8c59f618977.png)

Best regards,
Abu

**Comment by dodgeboy** [comment]
That link does a good job of describing how to determine what the threshold should be set to, but I cannot figure out where to set it.  Which file is it in?

**Comment by abuelgasimsaadeldin** [comment]
Hi @pospielov, I am also wondering, if the system always predicts one of the known classes with a certain probability then why is there a ```"No known faces"``` in the webcam demo? Sometimes it would show unknown faces with a known face but with very low similarity and other times it would just out ```"No known faces"```.

**Comment by dodgeboy** [comment]
Thank you for the responses!
