### ISSUE TITLE
What is the default model being used?

### ISSUE THREAD

**Issue by Rugan12** [exadel-inc/CompreFace#958]
Hi everyone,

Sorry I'm very new to CompreFace and Face Detection/Recognition in general, I've just managed to set it up and it is working fine and I notice the **custom-builds** which includes models such as FaceNet, MobileNet etc. which I have yet to test out. I would just like to ask, the default ```docker-compose.yml``` is using which model?

**Comment by pospielov** [comment]
The default model is FaceNet
