### ISSUE TITLE
Help send Hello Message once Face is Recognized

### ISSUE THREAD

**Issue by Rugan12** [exadel-inc/CompreFace#959]
Hi everyone!

I'm trying to send a custom welcome message to a subject once the face has been recognized, for now it will be a text ```"Welcome Subject!"``` and in the future sound through speakers. I'm struggling with the logic on how to accomplish this as it is happening in for a loop (the detection) and the text keeps repeating.

My goal would be to mention ```"Welcome Subject!"``` only once every 5 minutes time that the same subject has been recognized. I know this is more related to general Python instead of CompreFace but if there is anyone who had solved this before I would really appreciate the logic or example codes if any 🙏🙏

**Comment by Evgl1** [comment]
current_subjects = []
last_subjects = []
subj_out_count = {}
subj_out_step = FPS... = 1 sec


 if result:
    current_subjects.append(subject)
  
    if subject not in last_subjects:
         last_subjects.append(subject)
         
         !!!ACTION!!!
         
         
 for last_subject in last_subjects:
            if last_subject not in current_subjects:
                if last_subject not in subj_out_count:
                    subj_out_count[last_subject] = 1
                else:
                    if subj_out_count[last_subject] == 0:
                        last_subjects.remove(last_subject)

                        del subj_out_count[last_subject]
                    else:
                        subj_out_count[last_subject] += 1
                        subj_out_count[last_subject] %= subj_out_step - 1
            else:
                if last_subject in subj_out_count:
                    del subj_out_count[last_subject]

  current_subjects.clear()

**Comment by Rugan12** [comment]
Thank you @Evgl1, I will definitely try this out 🙏
