### ISSUE TITLE
Using CompreFace for Attendance System

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [exadel-inc/CompreFace#961]
Hi,

I've recently got to know about CompreFace and noticed in their Business Cases mentioned about Attendance systems, has that been implemented already (the UI, db saving etc.) or is it mainly talking about the face recognition and the attendance system would need to be developed on our own?

Regards,
Abu

**Comment by pospielov** [comment]
It's not implemented in CompreFace.
CompreFace can be used as a part of those systems, but there are lots of business logic that is different in each case and need to be implemented separately.
